//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.ActivityLogs.Sql.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLogData
    {
        public long Id { get; set; }
        public string MachineName { get; set; }
        public string ApplicationName { get; set; }
        public string Message { get; set; }
        public string ThreadId { get; set; }
        public string UserIdentity { get; set; }
        public string LogType { get; set; }
        public string ActivityName { get; set; }
        public System.DateTime LogDate { get; set; }
        public string TraceId { get; set; }
    }
}
